"""add_folders_table

Revision ID: 3d28837459ba
Revises: c15c87c23bfb
Create Date: 2025-11-15 01:54:45.770878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d28837459ba'
down_revision: Union[str, None] = 'c15c87c23bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('workflow_count', sa.Integer(), nullable=True),
    sa.Column('subfolder_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('document_chunks', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('document_chunks', 'document_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('document_chunks', 'embedding_model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('document_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('document_chunks_doc_id_idx'), table_name='document_chunks')
    op.drop_constraint(op.f('document_chunks_document_id_fkey'), 'document_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks', 'documents', ['document_id'], ['id'])
    op.alter_column('documents', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('documents', 'knowledge_base_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('documents', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('documents', 'file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('documents', 'file_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('documents', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('documents', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text('ARRAY[]::text[]'))
    op.alter_column('documents', 'chunk_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('documents', 'character_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('documents_kb_id_idx'), table_name='documents')
    op.drop_index(op.f('documents_status_idx'), table_name='documents')
    op.drop_constraint(op.f('documents_knowledge_base_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'knowledge_bases', ['knowledge_base_id'], ['id'])
    op.alter_column('knowledge_bases', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('knowledge_bases', 'organization_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('knowledge_bases', 'embedding_model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True,
               existing_server_default=sa.text("'text-embedding-ada-002'::text"))
    op.alter_column('knowledge_bases', 'chunk_size',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1000'))
    op.alter_column('knowledge_bases', 'chunk_overlap',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('200'))
    op.alter_column('knowledge_bases', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('knowledge_bases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_bases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('knowledge_bases_org_id_idx'), table_name='knowledge_bases')
    op.drop_index(op.f('knowledge_bases_user_id_idx'), table_name='knowledge_bases')
    op.drop_constraint(op.f('knowledge_bases_organization_id_fkey'), 'knowledge_bases', type_='foreignkey')
    op.drop_constraint(op.f('knowledge_bases_user_id_fkey'), 'knowledge_bases', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_bases', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'knowledge_bases', 'organization', ['organization_id'], ['id'])
    op.add_column('organization', sa.Column('org_metadata', sa.Text(), nullable=True))
    op.drop_column('organization', 'metadata')
    op.alter_column('tag_definitions', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tag_definitions', 'knowledge_base_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tag_definitions', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('tag_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tag_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('tag_definitions_kb_id_idx'), table_name='tag_definitions')
    op.drop_constraint(op.f('tag_definitions_knowledge_base_id_fkey'), 'tag_definitions', type_='foreignkey')
    op.create_foreign_key(None, 'tag_definitions', 'knowledge_bases', ['knowledge_base_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag_definitions', type_='foreignkey')
    op.create_foreign_key(op.f('tag_definitions_knowledge_base_id_fkey'), 'tag_definitions', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('tag_definitions_kb_id_idx'), 'tag_definitions', ['knowledge_base_id'], unique=False)
    op.alter_column('tag_definitions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tag_definitions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tag_definitions', 'name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tag_definitions', 'knowledge_base_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tag_definitions', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('organization', sa.Column('metadata', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('organization', 'org_metadata')
    op.drop_constraint(None, 'knowledge_bases', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_bases', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_bases_user_id_fkey'), 'knowledge_bases', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('knowledge_bases_organization_id_fkey'), 'knowledge_bases', 'organization', ['organization_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('knowledge_bases_user_id_idx'), 'knowledge_bases', ['user_id'], unique=False)
    op.create_index(op.f('knowledge_bases_org_id_idx'), 'knowledge_bases', ['organization_id'], unique=False)
    op.alter_column('knowledge_bases', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_bases', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_bases', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('knowledge_bases', 'chunk_overlap',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('200'))
    op.alter_column('knowledge_bases', 'chunk_size',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1000'))
    op.alter_column('knowledge_bases', 'embedding_model',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'text-embedding-ada-002'::text"))
    op.alter_column('knowledge_bases', 'organization_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('knowledge_bases', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('knowledge_bases', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_knowledge_base_id_fkey'), 'documents', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('documents_status_idx'), 'documents', ['status'], unique=False)
    op.create_index(op.f('documents_kb_id_idx'), 'documents', ['knowledge_base_id'], unique=False)
    op.alter_column('documents', 'processed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('documents', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'character_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('documents', 'chunk_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('documents', 'tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text('ARRAY[]::text[]'))
    op.alter_column('documents', 'status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('documents', 'file_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('documents', 'file_path',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('documents', 'name',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('documents', 'knowledge_base_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('documents', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('document_chunks_document_id_fkey'), 'document_chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('document_chunks_doc_id_idx'), 'document_chunks', ['document_id'], unique=False)
    op.alter_column('document_chunks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_chunks', 'embedding_model',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('document_chunks', 'document_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('document_chunks', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_table('folders')
    # ### end Alembic commands ###
